projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v

app_name = 'produto'

urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'),
    path('<int:pk>', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit', v.ProdutoUpdate.as_view(), name='produto_update'),
    path('<int:pk>/json/', v.produto_json, name='produto_json'),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
    path('logout', LogoutView.as_view(), name='logout'),
]

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque mínimo', default=0)

    class Meta:
        ordering = ('produto', )

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk':self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }

projeto/produto/forms.py
from django import forms
from .models import Produto

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'

projeto/produto/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView

from .forms import ProdutoForm
from .models import Produto


# def produto_list(request):
#     template_name = 'produto_list.html'
#     objects = Produto.objects.all()
#     search = request.GET.get('search')
#     if search:
#         objects = objects.filter(produto__icontains = search)
#     context = {'objects_list': objects}
#     return render(request, template_name, context)

class ProdutoList(ListView):
    model = Produto
    context_object_name = 'objects_list'
    template_name = 'produto_list.html'
    paginate_by = 10
        
    def get_queryset(self, *args, **kwargs):
        search = self.request.GET.get('search')
        if search:
            objects_list = Produto.objects.filter(produto__icontains = search)
            return objects_list        
        
        objects_list = Produto.objects.all()
        return objects_list
            

def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def produto_add(request):
    template_name = 'produto_form.html'
    
    return render(request, template_name)

class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class =  ProdutoForm

    # Setando a url de sucesso para a página de detalhe do objeto
    def get_success_url(self):
        return self.object.get_absolute_url()


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    """Retorna o produto, id e estoque"""
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})

projeto/produto/templates/produto_detail.html
{% extends "base.html"%}

{% block content%}

<a href="{% url 'produto:produto_list' %}">Voltar</a>
<h1>{{object}}
    <span class="pull-right">
        <a href="{% url 'produto:produto_update' pk=object.pk %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil"></span>Editar
            </button>
        </a>
    </span>
</h1>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
        <tr>
            <th class="text-left">Importado</th>
            <td>
                {% if object.importado%}
                <i class="fa fa-check-circle ok"></i>
                {% else %}
                <i class="fa fa-minus-circle no"></i>
                {% endif %}
            </td>
        </tr>

        <tr>
            <th class="text-left">NCM</th>
            <td>{{object.ncm}}</td>
        </tr>

        <tr>
            <th class="text-left">Preço</th>
            <td>R$ {{object.preco}}</td>
        </tr>

        <tr>
            <th class="text-left">Estoque</th>
            <td>{{object.estoque}}</td>
        </tr>

        <tr>
            <th class="text-left">Estoque Mínimo</th>
            <td>{{object.estoque_minimo}}</td>
        </tr>

        </tbody>
    </table>
</div>

{% endblock content%}

projeto/produto/templates/produto_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<form method="post" novalidate>
    {% csrf_token %}

    {% for field in form.visible_fields %}
    <div class="form-group {% if fields.erros %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
            {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
            {% else %}
            {{ field.label }}
            {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
        <span class="text-muted">{{ error }}</span>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}

{% block js %}

<script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

projeto/produto/templates/produto_list.html
{% extends "base.html"%}

{% block content%}



<div class="page-header" style="padding-top: 10px">
    <div class="row">
        <div class="col-3">
            <h2> Lista de Produtos</h2>
        </div>

        <div class="col-4">        
            <form action="." method="get" class='form-inline'>
                <input style="margin-right: 10px" type="text" id="search" name="search" class="form-control" placeholder="Busca">
                <input type="submit" class='btn btn-primary' value="OK">
            </form>        
        </div>

        <div class="col-5">
            <div class="pull-right">
                <a href="{% url 'produto:produto_add' %}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span> Adicionar
                    </button>
                </a>
            </div>
        </div>
    </div>

    {% if objects_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Importado</th>
                <th>NCM</th>
                <th>Produto</th>
                <th>Preço</th>
                <th class="text-center">Estoque</th>
                <th class="text-center">Estoque mínimo</th>
            </tr>
        </thead>
        <tbody>
            {% for object in objects_list %}
            <tr>
                <td>
                    {% if object.importado%}
                    <i class="fa fa-check-circle ok"></i>
                    {% else %}
                    <i class="fa fa-minus-circle no"></i>
                    {% endif %}
                </td>
                <td>{{ object.ncm }}</td>
                <td><a href="{{ object.get_absolute_url }}">{{ object.produto }}</a></td>
                <td>R$ <span class="pull-right">{{ object. }}</span></td>
                <td class="text-center">{{ object.estoque }}</td>
                <td class="text-center">{{ object.estoque_minimo }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else%}
    <p class="alert alert-warning">Sem itens na lista</p>
    {% endif %}

</div>

{% include "includes/pagination.html" %}

{% endblock content%}